namespace LibRawNet.Native {
    public enum LibRaw_filtering {
        LIBRAW_FILTERING_DEFAULT = 0,
        LIBRAW_FILTERING_NOZEROES = 1,
        LIBRAW_FILTERING_DEPRECATED1 = 2,
        LIBRAW_FILTERING_NORAWCURVE = 4,
        LIBRAW_FILTERING_NONE = 7,
        LIBRAW_FILTERING_LIBRAWOWN = 8 | LIBRAW_FILTERING_NONE,
        LIBRAW_FILTERING_AUTOMATIC_BIT = 16,
        LIBRAW_FILTERING_AUTOMATIC = LIBRAW_FILTERING_LIBRAWOWN | LIBRAW_FILTERING_AUTOMATIC_BIT,
    }
}